name: Tag image on published release
on:
  release:
    types: [released, prereleased]
jobs:
  tag_image:
    name: Tag image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set env
        run: echo "NEXT_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: vmware-tanzu/carvel-setup-action@v1
        with:
          only: ytt
          ytt: '0.36.0'
      - name: Read project name
        uses: KJ002/read-yaml@1.5
        id: project-name-data
        with:
          file: './k8s/templates/values.yml'
          key-path: '["projectName"]'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Setup Kubernetes Tools
        uses: yokawasa/action-setup-kube-tools@v0.8.0
        id: kubernetes-tools
        with:
          setup-tools: |
            kubectl
            rancher
      - name: Login rancher
        run: rancher login --token ${{ secrets.RANCHER_TOKEN }} --context ${{ secrets.RANCHER_CONTEXT }} ${{ secrets.RANCHER_URL }}
      - name: Switch rancher context to project
        run: ./.github/workflows/rancher-switch-context-to-project.sh "${{ steps.project-name-data.outputs.data }}"
      - name: Pull version docker image for tag
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ steps.project-name-data.outputs.data }}
        run: docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$NEXT_VERSION
      - name: Tag as pre-release
        if: 'github.event.release.prerelease'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ steps.project-name-data.outputs.data }}
        run: |
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$NEXT_VERSION $ECR_REGISTRY/$ECR_REPOSITORY:pre-release
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:pre-release
          ./.github/workflows/create-k8s-if-not-exists.sh "pre-release"
          K8S_NAMESPACE_NAME=$(./.github/workflows/get-namespace-name.js)
          ./.github/workflows/rancher-move-namespace-if-not-in-project.sh "${K8S_NAMESPACE_NAME}" "${{ steps.project-name-data.outputs.data }}"
          ./.github/workflows/rancher-redeploy.sh "${K8S_NAMESPACE_NAME}" "${{ steps.project-name-data.outputs.data }}" "pre-release"
          echo "TAG_TYPE=pre-release" >> $GITHUB_ENV
      - name: Tag as release
        if: '!github.event.release.prerelease'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ steps.project-name-data.outputs.data }}
        run: |
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$NEXT_VERSION $ECR_REGISTRY/$ECR_REPOSITORY:release
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:release
          ./.github/workflows/create-k8s-if-not-exists.sh "release"
          K8S_NAMESPACE_NAME=$(./.github/workflows/get-namespace-name.js)
          ./.github/workflows/rancher-move-namespace-if-not-in-project.sh "${K8S_NAMESPACE_NAME}" "${{ steps.project-name-data.outputs.data }}"
          ./.github/workflows/rancher-redeploy.sh "${K8S_NAMESPACE_NAME}" "${{ steps.project-name-data.outputs.data }}" "release"
          echo "TAG_TYPE=release" >> $GITHUB_ENV
      - name: Tag image success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: 'The `${{ env.NEXT_VERSION }}` for project `${{ steps.project-name-data.outputs.data }}` was successfully tagged as **${{ env.TAG_TYPE }}**'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: ${{ secrets.DISCORD_AVATAR_URL }}
      - name: Tag image failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: 'Tag image `${{ env.NEXT_VERSION }}` for project `${{ steps.project-name-data.outputs.data }}` failed'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: ${{ secrets.DISCORD_AVATAR_URL }}
      - name: Tag image cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: 'Tag image `${{ env.NEXT_VERSION }}` for project `${{ steps.project-name-data.outputs.data }}` cancelled'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: ${{ secrets.DISCORD_AVATAR_URL }}
